import { execute, selectRaw } from './index';

const MIGRATIONS = [
  `CREATE TABLE IF NOT EXISTS exercises (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    name TEXT NOT NULL,
    category TEXT,
    description TEXT,
    body_part TEXT,
    primary_muscle TEXT,
    secondary_muscles TEXT,
    equipment TEXT,
    movement TEXT,
    exercise_type TEXT,
    exercise_category TEXT,
    image_url TEXT,
    image_key TEXT,
    instructions TEXT,
    difficulty TEXT,
    training_style TEXT,
    progression_group TEXT,
    progression_level INTEGER,
    source TEXT DEFAULT 'system',
    archived INTEGER DEFAULT 0,
    seeded INTEGER DEFAULT 0,
    seeded_id TEXT,
    seeded_version INTEGER DEFAULT 0,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE TABLE IF NOT EXISTS workouts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    name TEXT NOT NULL,
    type TEXT,
    section TEXT,
    description TEXT,
    difficulty TEXT,
    training_style TEXT,
    archived INTEGER DEFAULT 0,
    seeded INTEGER DEFAULT 0,
    seeded_id TEXT,
    seeded_version INTEGER DEFAULT 0,
    deleted INTEGER DEFAULT 0,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,

  `
  CREATE TABLE IF NOT EXISTS workout_blocks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    workout_id INTEGER NOT NULL,
    type TEXT NOT NULL DEFAULT 'straight_sets',
    name TEXT,
    rounds INTEGER,
    rest_between_rounds INTEGER,
    order_index INTEGER NOT NULL DEFAULT 0,
    deleted INTEGER DEFAULT 0,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(workout_id) REFERENCES workouts(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS workout_exercises (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    workout_id INTEGER NOT NULL,
    block_id INTEGER,
    exercise_id INTEGER NOT NULL,
    order_index INTEGER NOT NULL,
    default_sets INTEGER NOT NULL DEFAULT 1,
    default_reps INTEGER NOT NULL DEFAULT 1,
    weight REAL DEFAULT 0,
    rest_seconds INTEGER,
    section TEXT DEFAULT 'main',
    superset_id INTEGER,
    group_id INTEGER,
    group_type TEXT,
    setsArray TEXT DEFAULT '[]',
    deleted INTEGER DEFAULT 0,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(workout_id) REFERENCES workouts(id) ON DELETE CASCADE,
    FOREIGN KEY(block_id) REFERENCES workout_blocks(id) ON DELETE SET NULL,
    FOREIGN KEY(exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS workout_exercise_sets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    workout_id INTEGER NOT NULL,
    workout_exercise_id INTEGER,
    exercise_id INTEGER NOT NULL,
    set_number INTEGER NOT NULL,
    planned_reps INTEGER NOT NULL,
    planned_weight REAL,
    duration_seconds INTEGER,
    drop_sets TEXT,
    deleted INTEGER DEFAULT 0,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(workout_id) REFERENCES workouts(id) ON DELETE CASCADE,
    FOREIGN KEY(workout_exercise_id) REFERENCES workout_exercises(id) ON DELETE CASCADE,
    FOREIGN KEY(exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS workout_sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    workout_id INTEGER NOT NULL,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    notes TEXT,
    duration INTEGER,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(workout_id) REFERENCES workouts(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS exercise_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    workout_session_id INTEGER NOT NULL,
    block_id INTEGER,
    block_type TEXT,
    block_name TEXT,
    block_rounds INTEGER,
    block_rest_between_rounds INTEGER,
    block_order INTEGER,
    exercise_id INTEGER NOT NULL,
    planned_sets INTEGER,
    planned_reps INTEGER,
    weight REAL,
    rest_seconds INTEGER,
    order_index INTEGER,
    superset_id INTEGER,
    group_id INTEGER,
    group_type TEXT,
    source TEXT DEFAULT 'template',
    section TEXT DEFAULT 'main',
    notes TEXT,
    deleted INTEGER DEFAULT 0,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(workout_session_id) REFERENCES workout_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS set_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    exercise_log_id INTEGER NOT NULL,
    set_number INTEGER NOT NULL,
    round_number INTEGER,
    planned_reps INTEGER NOT NULL,
    reps INTEGER,
    weight REAL,
    planned_duration_seconds INTEGER,
    duration_seconds INTEGER,
    drop_sets TEXT,
    completed INTEGER NOT NULL DEFAULT 0,
    deleted INTEGER DEFAULT 0,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(exercise_log_id) REFERENCES exercise_logs(id) ON DELETE CASCADE
  );`,
  `CREATE TABLE IF NOT EXISTS personal_records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    remote_id TEXT,
    client_id TEXT,
    exercise_id INTEGER NOT NULL,
    workout_session_id INTEGER NOT NULL,
    set_log_id INTEGER NOT NULL,
    record_type TEXT NOT NULL CHECK(record_type IN ('weight', 'reps', 'volume')),
    value REAL NOT NULL,
    previous_value REAL,
    weight REAL,
    reps INTEGER,
    achieved_at TEXT NOT NULL,
    calculation_version INTEGER NOT NULL DEFAULT 1,
    synced INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1,
    last_synced_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(exercise_id) REFERENCES exercises(id) ON DELETE CASCADE,
    FOREIGN KEY(workout_session_id) REFERENCES workout_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(set_log_id) REFERENCES set_logs(id) ON DELETE CASCADE,
    UNIQUE(workout_session_id, set_log_id, record_type)
  );`,
  `CREATE TABLE IF NOT EXISTS progressive_overload_applications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    workout_session_id INTEGER NOT NULL,
    workout_id INTEGER NOT NULL,
    exercise_id INTEGER NOT NULL,
    exercise_log_id INTEGER,
    set_number INTEGER NOT NULL,
    field TEXT NOT NULL,
    previous_value REAL,
    new_value REAL,
    recommendation_type TEXT NOT NULL,
    reason_code TEXT NOT NULL,
    drop_sets_snapshot TEXT,
    applied_at TEXT NOT NULL DEFAULT (datetime('now')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(workout_session_id) REFERENCES workout_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(workout_id) REFERENCES workouts(id) ON DELETE CASCADE,
    FOREIGN KEY(exercise_id) REFERENCES exercises(id) ON DELETE CASCADE,
    FOREIGN KEY(exercise_log_id) REFERENCES exercise_logs(id) ON DELETE CASCADE,
    UNIQUE(workout_session_id, exercise_id, set_number, field)
  );`,
  `CREATE TABLE IF NOT EXISTS progressive_overload_recommendation_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    workout_session_id INTEGER NOT NULL,
    exercise_id INTEGER NOT NULL,
    exercise_log_id INTEGER NOT NULL,
    eligible INTEGER NOT NULL DEFAULT 0,
    reason_code TEXT NOT NULL,
    reason_label TEXT NOT NULL,
    recommendation_type TEXT NOT NULL,
    current_value REAL,
    recommended_value REAL,
    increment REAL NOT NULL DEFAULT 0,
    equipment_increment REAL NOT NULL DEFAULT 0,
    is_bodyweight INTEGER NOT NULL DEFAULT 0,
    is_timed INTEGER NOT NULL DEFAULT 0,
    is_block_exercise INTEGER NOT NULL DEFAULT 0,
    has_drop_sets INTEGER NOT NULL DEFAULT 0,
    recommendation_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY(workout_session_id) REFERENCES workout_sessions(id) ON DELETE CASCADE,
    FOREIGN KEY(exercise_id) REFERENCES exercises(id) ON DELETE CASCADE,
    FOREIGN KEY(exercise_log_id) REFERENCES exercise_logs(id) ON DELETE CASCADE,
    UNIQUE(workout_session_id, exercise_id, exercise_log_id)
  );`,
  `CREATE TABLE IF NOT EXISTS workout_tracker_meta (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );`,
  `CREATE INDEX IF NOT EXISTS idx_workout_blocks_workout ON workout_blocks(workout_id);`,
  `CREATE INDEX IF NOT EXISTS idx_workout_exercises_workout ON workout_exercises(workout_id);`,
  `CREATE INDEX IF NOT EXISTS idx_workout_exercise_sets_workout ON workout_exercise_sets(workout_id);`,
  `CREATE INDEX IF NOT EXISTS idx_workout_sessions_workout ON workout_sessions(workout_id);`,
  `CREATE INDEX IF NOT EXISTS idx_exercise_logs_session ON exercise_logs(workout_session_id);`,
  `CREATE INDEX IF NOT EXISTS idx_set_logs_exercise_log ON set_logs(exercise_log_id);`,
  `CREATE INDEX IF NOT EXISTS idx_personal_records_exercise ON personal_records(exercise_id, achieved_at);`,
  `CREATE INDEX IF NOT EXISTS idx_personal_records_session ON personal_records(workout_session_id);`,
  `CREATE INDEX IF NOT EXISTS idx_progressive_overload_applications_session ON progressive_overload_applications(workout_session_id);`,
  `CREATE INDEX IF NOT EXISTS idx_progressive_overload_recommendation_snapshots_session ON progressive_overload_recommendation_snapshots(workout_session_id);`,
];

const MIGRATION_COLUMNS: Record<string, Array<[string, string]>> = {
  exercises: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['movement', 'TEXT'],
    ['exercise_category', 'TEXT'],
    ['instructions', 'TEXT'],
    ['difficulty', 'TEXT'],
    ['training_style', 'TEXT'],
    ['progression_group', 'TEXT'],
    ['progression_level', 'INTEGER'],
    ['source', "TEXT DEFAULT 'system'"],
    ['seeded', 'INTEGER DEFAULT 0'],
    ['seeded_id', 'TEXT'],
    ['seeded_version', 'INTEGER DEFAULT 0'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  workouts: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['difficulty', 'TEXT'],
    ['training_style', 'TEXT'],
    ['seeded', 'INTEGER DEFAULT 0'],
    ['seeded_id', 'TEXT'],
    ['seeded_version', 'INTEGER DEFAULT 0'],
    ['deleted', 'INTEGER DEFAULT 0'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  workout_blocks: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['rounds', 'INTEGER'],
    ['rest_between_rounds', 'INTEGER'],
    ['deleted', 'INTEGER DEFAULT 0'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  workout_exercises: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['block_id', 'INTEGER'],
    ['group_id', 'INTEGER'],
    ['group_type', 'TEXT'],
    ['setsArray', "TEXT DEFAULT '[]'"],
    ['rest_seconds', 'INTEGER'],
    ['deleted', 'INTEGER DEFAULT 0'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  workout_exercise_sets: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['workout_exercise_id', 'INTEGER'],
    ['duration_seconds', 'INTEGER'],
    ['drop_sets', 'TEXT'],
    ['deleted', 'INTEGER DEFAULT 0'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  workout_sessions: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  exercise_logs: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['block_id', 'INTEGER'],
    ['block_type', 'TEXT'],
    ['block_name', 'TEXT'],
    ['block_rounds', 'INTEGER'],
    ['block_rest_between_rounds', 'INTEGER'],
    ['block_order', 'INTEGER'],
    ['group_id', 'INTEGER'],
    ['group_type', 'TEXT'],
    ['section', "TEXT DEFAULT 'main'"],
    ['order_index', 'INTEGER'],
    ['rest_seconds', 'INTEGER'],
    ['source', "TEXT DEFAULT 'template'"],
    ['deleted', 'INTEGER DEFAULT 0'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  set_logs: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['round_number', 'INTEGER'],
    ['planned_duration_seconds', 'INTEGER'],
    ['duration_seconds', 'INTEGER'],
    ['drop_sets', 'TEXT'],
    ['deleted', 'INTEGER DEFAULT 0'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
  personal_records: [
    ['user_id', 'TEXT'],
    ['remote_id', 'TEXT'],
    ['client_id', 'TEXT'],
    ['calculation_version', 'INTEGER DEFAULT 1'],
    ['synced', 'INTEGER DEFAULT 0'],
    ['version', 'INTEGER DEFAULT 1'],
    ['last_synced_at', 'TEXT'],
  ],
};

async function addColumnIfMissing(
  table: string,
  column: string,
  definition: string,
) {
  const columns = await selectRaw<{ name: string }>(
    `PRAGMA table_info(${table})`,
  );
  if (!columns.some(item => item.name === column)) {
    await execute(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
  }
}

export async function migrateWorkoutTrackerDb() {
  for (const [index, sql] of MIGRATIONS.entries()) {
    try {
      await execute(sql);
    } catch (error) {
      const statement = sql.trim().split(/\s+/).slice(0, 8).join(' ');
      throw new Error(
        `Workout tracker migration ${index + 1} failed (${statement}): ${String(
          error,
        )}`,
      );
    }
  }

  for (const [table, columns] of Object.entries(MIGRATION_COLUMNS)) {
    for (const [column, definition] of columns) {
      try {
        await addColumnIfMissing(table, column, definition);
      } catch (error) {
        throw new Error(
          `Workout tracker column migration failed (${table}.${column}): ${String(
            error,
          )}`,
        );
      }
    }
  }
}
